<div ng-app="myApp" ng-controller="pessoasController">
	<div class="row">
		<div class="col-xs-12">
				<ul class="list-group" id="contact-list">
					<li class="list-group-item" ng-repeat="t in times">
						<div class="col-xs-1">
							<img src="{{t.foto_perfil}}" alt="{{t.nome}}" class="img-responsive img-circle" width="30" />
						</div>
						<div class="col-xs-11">
							<div class="col-xs-10">
								<span class="name">{{t.nome}}</span>
							</div>
							<div class="col-xs-2">
								<span class="pontos">{{t.pontos.rodada | number:2}}</span>
							</div>
						</div>
						<div class="clearfix"></div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
(function() {
	var app = angular.module('myApp', []);
	app.controller('pessoasController', function($scope, $http) {
		$http({
		  method: 'GET',
		  url: '/application/index/liga/'
		}).then(function successCallback(response) {
			$scope.times = response.data.times;
		});	
	});
})();
</script>